### ISSUE TITLE
Cannot add RatingCF to Filter Results Gadget on Dashboard

### ISSUE THREAD

**Issue by hirodragon** [thankjura/JiraRatingCF#3]
After adding RatingCF column in gadget configuration and hitting "Save" configuration is not saved. Therefore is not possible to add RatingCF to Filter Results gadget.

**Comment by thankjura** [comment]
What is your version of the plugin?

**Comment by hirodragon** [comment]
Update: I am using current version - 3.0.6 with JIRA Server 6.3.14. It is possible to save configuration now, but RatingCF is still not displayed correctly. As can be seen on screenshot below.

![slie](https://cloud.githubusercontent.com/assets/5793517/8545554/33764e92-24b0-11e5-9150-551db1123b8b.png)

**Comment by thankjura** [comment]
hm. I tested plugin 2.0.6 version, 
![screen](https://i.imgur.com/Z9pK8zN.png)

Try clear browser cache

**Comment by hirodragon** [comment]
Cache cleared, still same results. This is a snippet from generated HTML of problematic gadget column.

![slie2](https://cloud.githubusercontent.com/assets/5793517/8546926/91c3e97c-24bb-11e5-99bd-899958dc6509.png)

**Comment by thankjura** [comment]
JavaScript can't load.
You have installed third-party plug-ins?
Your browser supports Javascript?
Check this in console:
![console](https://i.imgur.com/g4dROk8.png)

'updateRate' return function if JavaScript loaded

**Comment by ggsatlassian** [comment]
Hi,
are there any updates? 

We have installed 2.0.6v Slie and 6.3.8v JIRA. We have also many another add-ons as JIRA Agile, Structure...
Here is the console check you have mentioned (newest chrome v48.0.2564.97 m)
![2016-02-01_10h28_35](https://cloud.githubusercontent.com/assets/17002699/12713699/7951221a-c8d0-11e5-9765-cdc8588ee52b.png)


p.s.: [Here ](https://answers.atlassian.com/questions/32972796/how-to-display-rating-field-as-stars-in-dashboard)is also my question.

**Comment by thankjura** [comment]
Hello!
I tried earlier to fix the problem, but to no avail.
I try to work on the problem in a week

2016-02-01 12:43 GMT+03:00 ggsatlassian <notifications@github.com>:

**Comment by thankjura** [comment]
Hello!
check for updates

2016-02-01 12:50 GMT+03:00 Юрий Обоз <me@slie.ru>:
