### ISSUE TITLE
Rating field does not render in Create issue "overlay"

### ISSUE THREAD

**Issue by herrherrmann** [thankjura/JiraRatingCF#4]
When creating an issue from the Dashboard, the issue form will open in a popup/overlay. In this overlay the rating field is not properly rendered - instead it just shows numbers with links.
![issue-overlay](https://cloud.githubusercontent.com/assets/6429568/5225957/a30ae92c-76e9-11e4-8f6f-ed86ebf1a47b.png)

Nonetheless the field is working when I create an issue without the overlay (e.g. through opening "Create issue" in a new tab or window):
![issue-link](https://cloud.githubusercontent.com/assets/6429568/5226014/3aa528f6-76ea-11e4-9c37-cfcafafa986b.PNG)

**Comment by Brella** [comment]
Hi, i have the same problem here. is there any update?

**Comment by thankjura** [comment]
check for updates :)
