### ISSUE TITLE
Display rating label on issue statistics (jira 6.3.12)

### ISSUE THREAD

**Issue by ullinkIS** [thankjura/JiraRatingCF#6]
Hi,
I'm using JIRA 6.3.12 and we have a problem to display the rating labels on dashboard gadgets, as you can see in the screenshot instead of the label of the different rating I have displayed "none".
Any idea for the fix or a workaround ?

![ratingstats](https://cloud.githubusercontent.com/assets/11208825/6388796/fbfa9726-bd9d-11e4-9ce0-274e2e3294ed.jpg)
![cf_config](https://cloud.githubusercontent.com/assets/11208825/6388795/fbe5d282-bd9d-11e4-9c4b-e21fd8d97693.jpg)

**Comment by thankjura** [comment]
What is your version of the plugin?

**Comment by berg229** [comment]
Hello, i have the same Problem. The Labels in Chart wont displayed.

![chart](https://cloud.githubusercontent.com/assets/20700002/17207457/f7b63968-54b4-11e6-91bc-233f6c5cb531.PNG)

![options](https://cloud.githubusercontent.com/assets/20700002/17207495/2cbdbdc0-54b5-11e6-8302-b71bfcb7289f.PNG)

JIRA Version: 7.0.10
Slie Jira CustomFields Version: 2.1.1

if anyone could get it to work, i could use the Plugin.

Thanks in advance

**Comment by thankjura** [comment]
Hello. I try today to see what was going on.

**Comment by thankjura** [comment]
Check for updates ;)

**Comment by berg229** [comment]
It works perfectly, thank you!
